# Generated by Django 2.2 on 2021-10-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
    ]
