# Generated by Django 2.2 on 2021-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('comedy', 'comedy')], default=None, max_length=255),
        ),
    ]
