# Generated by Django 2.2 on 2021-10-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0003_auto_20211009_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
