# Generated by Django 2.2 on 2021-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0005_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_stories', to='storylineapp.User'),
        ),
    ]
