# Generated by Django 2.2 on 2021-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0005_auto_20211110_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('sci-fi-fantasy', 'sci-fi-fantasy'), ('thriller', 'mystery-thriller'), ('horror', 'horror'), ('drama', 'drama'), ('romance', 'romance')], default=None, max_length=255),
        ),
    ]
