# Generated by Django 2.2 on 2021-10-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0006_story_users_who_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('sci-fi/fantasy', 'sci-fi/fantasy'), ('thriller', 'mystery/thriller'), ('horror', 'horror'), ('drama', 'drama'), ('romance', 'romance')], default=None, max_length=255),
        ),
    ]
