# Generated by Django 2.2 on 2021-10-07 04:50

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0009_auto_20211001_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='images/blank-profile.jpg', upload_to='profiles'),
        ),
    ]
