# Generated by Django 2.2 on 2021-10-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0010_auto_20211006_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_content', models.TextField(max_length=100000)),
                ('been_accepted', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_trying_to_be_added_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_story', to='storylineapp.Story')),
                ('user_adding_content', models.ManyToManyField(related_name='users_who_added_to_story', to='storylineapp.User')),
            ],
        ),
    ]
